baseURL = "/"
languageCode = 'en-us'
title = '1upcloud technology'

[[params.social]]
  name = "fa-x-twitter"
  url = "https://x.com/Microsoft"

[[params.social]]
  name = "fa-facebook"
  url = "https://www.facebook.com/Microsoft/"

[[params.social]]
  name = "fa-instagram"
  url = "https://www.instagram.com/microsoft/"

[[params.social]]
  name = "fa-linkedin"
  url = "https://www.linkedin.com/company/microsoft"  